# Generated by Django 5.2.14 on 2026-05-30 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos_usuarios/%Y/%m/%d/')),
                ('tipo_operacion', models.CharField(choices=[('DIVIDIR', 'Dividir PDF'), ('CONVERTIR', 'Convertir a Word'), ('EDITAR', 'Editar PDF')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADO', 'Procesado con Éxito'), ('ERROR', 'Error en Procesamiento')], default='PENDIENTE', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documentos de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='HistorialAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='dividir.documentousuario')),
            ],
        ),
    ]
