# Generated by Django 5.2.14 on 2026-05-30 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividir', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentousuario',
            options={'verbose_name': 'Documento de Usuario', 'verbose_name_plural': 'Documentos de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='historialacciones',
            options={'verbose_name': 'Historial de Acción', 'verbose_name_plural': 'Historial de Acciones'},
        ),
        migrations.CreateModel(
            name='DescargasDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas', to='dividir.documentousuario')),
            ],
            options={
                'verbose_name': 'Registro de Descarga',
                'verbose_name_plural': 'Registro de Descargas',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario', models.IntegerField(default=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
