# Generated by Django 5.2.14 on 2026-05-30 21:32

import apps.dividir.models.perfil
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividir', '0002_alter_documentousuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AddField(
            model_name='documentousuario',
            name='privacidad',
            field=models.CharField(choices=[('PRIVADO', 'Solo yo'), ('PUBLICO', 'Público (Visible en la comunidad)')], default='PRIVADO', max_length=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='biografia',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, default='img/user_default.png', upload_to=apps.dividir.models.perfil.ruta_perfil),
        ),
        migrations.AlterField(
            model_name='documentousuario',
            name='archivo',
            field=models.FileField(upload_to='documentos_usuarios/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='documentousuario',
            name='nombre_original',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='limite_diario',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
