# Generated by Django 5.2.14 on 2026-05-30 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividir', '0003_alter_perfilusuario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Para calcular la edad de forma dinámica', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada cambio'),
        ),
        migrations.CreateModel(
            name='HistorialCambiosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Usuario',
                'verbose_name_plural': 'Historial de Cambios de Usuarios',
            },
        ),
    ]
