# Generated by Django 5.2.14 on 2026-05-30 23:47

import apps.dividir.models.perfil
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividir', '0004_remove_perfilusuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.dividir.models.perfil.ruta_perfil),
        ),
    ]
